/**
 * FEC-OS API catalog — auto-generated by scripts/generate-api-catalog.mjs
 * Regenerate: node scripts/generate-api-catalog.mjs
 * Last generated: 2026-06-29T12:35:04.774Z
 */

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export type ApiAuthType = "session" | "api_key" | "cron_secret" | "none";

export interface ApiExampleRequest {
  headers?: Record<string, string>;
  body?: unknown;
  query?: Record<string, string>;
}

export interface ApiEndpoint {
  id: string;
  method: HttpMethod;
  path: string;
  description: string;
  categoryId: string;
  categoryLabel: string;
  authType: ApiAuthType;
  authDetail: string;
  exampleRequest?: ApiExampleRequest;
}

export interface ApiCategory {
  id: string;
  label: string;
}

export const API_CATEGORIES: ApiCategory[] = [
  {
    "id": "admin",
    "label": "Admin"
  },
  {
    "id": "amc",
    "label": "AMC"
  },
  {
    "id": "assets",
    "label": "Assets"
  },
  {
    "id": "auth",
    "label": "Auth"
  },
  {
    "id": "bookings",
    "label": "Bookings"
  },
  {
    "id": "branches",
    "label": "Branches"
  },
  {
    "id": "ceo",
    "label": "CEO"
  },
  {
    "id": "compliance",
    "label": "Compliance"
  },
  {
    "id": "customer",
    "label": "Customer"
  },
  {
    "id": "daily-ops",
    "label": "Daily Ops"
  },
  {
    "id": "dashboard",
    "label": "Dashboard"
  },
  {
    "id": "facility",
    "label": "Facility"
  },
  {
    "id": "inspections",
    "label": "Inspections"
  },
  {
    "id": "inventory",
    "label": "Inventory"
  },
  {
    "id": "issues",
    "label": "Issues"
  },
  {
    "id": "maintenance",
    "label": "Maintenance"
  },
  {
    "id": "notifications",
    "label": "Notifications"
  },
  {
    "id": "occ",
    "label": "OCC"
  },
  {
    "id": "operations",
    "label": "Operations"
  },
  {
    "id": "people",
    "label": "People"
  },
  {
    "id": "public",
    "label": "Public & Cron"
  },
  {
    "id": "revenue",
    "label": "Revenue"
  },
  {
    "id": "risk",
    "label": "Risk"
  },
  {
    "id": "sites",
    "label": "Sites"
  },
  {
    "id": "snags",
    "label": "Snags"
  },
  {
    "id": "tasks",
    "label": "Tasks"
  },
  {
    "id": "utilities",
    "label": "Utilities"
  },
  {
    "id": "vendors",
    "label": "Vendors"
  },
  {
    "id": "weekly-reports",
    "label": "Weekly Reports"
  },
  {
    "id": "work-orders",
    "label": "Work Orders"
  }
];

export const API_ENDPOINTS: ApiEndpoint[] = [
  {
    "id": "get-api-admin-users",
    "method": "GET",
    "path": "/api/admin/users",
    "description": "FEC-OS API: admin / users",
    "categoryId": "admin",
    "categoryLabel": "Admin",
    "authType": "session",
    "authDetail": "Session + capability: admin.view"
  },
  {
    "id": "get-api-amc-contracts",
    "method": "GET",
    "path": "/api/amc/contracts",
    "description": "FEC-OS API: amc / contracts",
    "categoryId": "amc",
    "categoryLabel": "AMC",
    "authType": "session",
    "authDetail": "Session + capability: amc.view"
  },
  {
    "id": "get-api-amc-dashboard",
    "method": "GET",
    "path": "/api/amc/dashboard",
    "description": "FEC-OS API: amc / dashboard",
    "categoryId": "amc",
    "categoryLabel": "AMC",
    "authType": "session",
    "authDetail": "Session + capability: amc.view"
  },
  {
    "id": "get-api-amc-dashboard-contracts",
    "method": "GET",
    "path": "/api/amc/dashboard/contracts",
    "description": "FEC-OS API: amc / dashboard / contracts",
    "categoryId": "amc",
    "categoryLabel": "AMC",
    "authType": "session",
    "authDetail": "Session + capability: amc.view"
  },
  {
    "id": "get-api-amc-dashboard-summary",
    "method": "GET",
    "path": "/api/amc/dashboard/summary",
    "description": "FEC-OS API: amc / dashboard / summary",
    "categoryId": "amc",
    "categoryLabel": "AMC",
    "authType": "session",
    "authDetail": "Session + capability: amc.view"
  },
  {
    "id": "get-api-amc-expiry-alerts",
    "method": "GET",
    "path": "/api/amc/expiry-alerts",
    "description": "FEC-OS API: amc / expiry-alerts",
    "categoryId": "amc",
    "categoryLabel": "AMC",
    "authType": "session",
    "authDetail": "Session + capability: amc.view"
  },
  {
    "id": "get-api-amc-payments",
    "method": "GET",
    "path": "/api/amc/payments",
    "description": "FEC-OS API: amc / payments",
    "categoryId": "amc",
    "categoryLabel": "AMC",
    "authType": "session",
    "authDetail": "Session + capability: amc.view"
  },
  {
    "id": "get-api-amc-renewals",
    "method": "GET",
    "path": "/api/amc/renewals",
    "description": "FEC-OS API: amc / renewals",
    "categoryId": "amc",
    "categoryLabel": "AMC",
    "authType": "session",
    "authDetail": "Session + capability: amc.view"
  },
  {
    "id": "get-api-amc-schedules",
    "method": "GET",
    "path": "/api/amc/schedules",
    "description": "FEC-OS API: amc / schedules",
    "categoryId": "amc",
    "categoryLabel": "AMC",
    "authType": "session",
    "authDetail": "Session + capability: amc.view"
  },
  {
    "id": "get-api-assets",
    "method": "GET",
    "path": "/api/assets",
    "description": "FEC-OS API: assets",
    "categoryId": "assets",
    "categoryLabel": "Assets",
    "authType": "session",
    "authDetail": "Session + capability: maintenance.view"
  },
  {
    "id": "get-api-auth-session",
    "method": "GET",
    "path": "/api/auth/session",
    "description": "FEC-OS API: auth / session",
    "categoryId": "auth",
    "categoryLabel": "Auth",
    "authType": "session",
    "authDetail": "Session cookie (optional — 401 returns empty session)"
  },
  {
    "id": "get-api-bookings",
    "method": "GET",
    "path": "/api/bookings",
    "description": "FEC-OS API: bookings",
    "categoryId": "bookings",
    "categoryLabel": "Bookings",
    "authType": "session",
    "authDetail": "Session + capability: bookings.view"
  },
  {
    "id": "get-api-branches-league",
    "method": "GET",
    "path": "/api/branches/league",
    "description": "FEC-OS API: branches / league",
    "categoryId": "branches",
    "categoryLabel": "Branches",
    "authType": "session",
    "authDetail": "Session + capability: dashboard.view"
  },
  {
    "id": "get-api-ceo-overview",
    "method": "GET",
    "path": "/api/ceo/overview",
    "description": "FEC-OS API: ceo / overview",
    "categoryId": "ceo",
    "categoryLabel": "CEO",
    "authType": "session",
    "authDetail": "Session + capability: ceo.view_dashboard"
  },
  {
    "id": "get-api-compliance-alerts",
    "method": "GET",
    "path": "/api/compliance/alerts",
    "description": "FEC-OS API: compliance / alerts",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-calendar",
    "method": "GET",
    "path": "/api/compliance/calendar",
    "description": "FEC-OS API: compliance / calendar",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-command",
    "method": "GET",
    "path": "/api/compliance/command",
    "description": "FEC-OS API: compliance / command",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-coverage",
    "method": "GET",
    "path": "/api/compliance/coverage",
    "description": "FEC-OS API: compliance / coverage",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-documents",
    "method": "GET",
    "path": "/api/compliance/documents",
    "description": "FEC-OS API: compliance / documents",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "delete-api-compliance-e3-tracker",
    "method": "DELETE",
    "path": "/api/compliance/e3-tracker",
    "description": "FEC-OS API: compliance / e3-tracker",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.edit_e3_tracker"
  },
  {
    "id": "get-api-compliance-e3-tracker",
    "method": "GET",
    "path": "/api/compliance/e3-tracker",
    "description": "FEC-OS API: compliance / e3-tracker",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "post-api-compliance-e3-tracker",
    "method": "POST",
    "path": "/api/compliance/e3-tracker",
    "description": "FEC-OS API: compliance / e3-tracker",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.edit_e3_tracker"
  },
  {
    "id": "put-api-compliance-e3-tracker",
    "method": "PUT",
    "path": "/api/compliance/e3-tracker",
    "description": "FEC-OS API: compliance / e3-tracker",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.edit_e3_tracker"
  },
  {
    "id": "get-api-compliance-e3-tracker-amc",
    "method": "GET",
    "path": "/api/compliance/e3-tracker/amc",
    "description": "FEC-OS API: compliance / e3-tracker / amc",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-e3-tracker-category",
    "method": "GET",
    "path": "/api/compliance/e3-tracker/category",
    "description": "FEC-OS API: compliance / e3-tracker / category",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-e3-tracker-license-documents",
    "method": "GET",
    "path": "/api/compliance/e3-tracker/license-documents",
    "description": "FEC-OS API: compliance / e3-tracker / license-documents",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-e3-tracker-missing-documents",
    "method": "GET",
    "path": "/api/compliance/e3-tracker/missing-documents",
    "description": "FEC-OS API: compliance / e3-tracker / missing-documents",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-e3-tracker-register",
    "method": "GET",
    "path": "/api/compliance/e3-tracker/register",
    "description": "FEC-OS API: compliance / e3-tracker / register",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-e3-tracker-scheduler",
    "method": "GET",
    "path": "/api/compliance/e3-tracker/scheduler",
    "description": "FEC-OS API: compliance / e3-tracker / scheduler",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-e3-tracker-summary",
    "method": "GET",
    "path": "/api/compliance/e3-tracker/summary",
    "description": "FEC-OS API: compliance / e3-tracker / summary",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-e3-tracker-vendors",
    "method": "GET",
    "path": "/api/compliance/e3-tracker/vendors",
    "description": "FEC-OS API: compliance / e3-tracker / vendors",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-executive-kpis",
    "method": "GET",
    "path": "/api/compliance/executive-kpis",
    "description": "FEC-OS API: compliance / executive-kpis",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-expiry-alerts",
    "method": "GET",
    "path": "/api/compliance/expiry-alerts",
    "description": "FEC-OS API: compliance / expiry-alerts",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-expiry-notifications",
    "method": "GET",
    "path": "/api/compliance/expiry-notifications",
    "description": "FEC-OS API: compliance / expiry-notifications",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-kpis",
    "method": "GET",
    "path": "/api/compliance/kpis",
    "description": "FEC-OS API: compliance / kpis",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: dashboard.view"
  },
  {
    "id": "get-api-compliance-location-tracker",
    "method": "GET",
    "path": "/api/compliance/location-tracker",
    "description": "FEC-OS API: compliance / location-tracker",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "post-api-compliance-process-expiry-notifications",
    "method": "POST",
    "path": "/api/compliance/process-expiry-notifications",
    "description": "Cron-safe endpoint: processes document expiry notifications.",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "cron_secret",
    "authDetail": "CRON_SECRET (Bearer or x-cron-secret)"
  },
  {
    "id": "get-api-compliance-register",
    "method": "GET",
    "path": "/api/compliance/register",
    "description": "FEC-OS API: compliance / register",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-renewals",
    "method": "GET",
    "path": "/api/compliance/renewals",
    "description": "FEC-OS API: compliance / renewals",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-service-history",
    "method": "GET",
    "path": "/api/compliance/service-history",
    "description": "FEC-OS API: compliance / service-history",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-staff-readiness",
    "method": "GET",
    "path": "/api/compliance/staff-readiness",
    "description": "FEC-OS API: compliance / staff-readiness",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-supervisor",
    "method": "GET",
    "path": "/api/compliance/supervisor",
    "description": "FEC-OS API: compliance / supervisor",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: tasks.complete"
  },
  {
    "id": "get-api-compliance-trend",
    "method": "GET",
    "path": "/api/compliance/trend",
    "description": "FEC-OS API: compliance / trend",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-compliance-vendor-scorecard",
    "method": "GET",
    "path": "/api/compliance/vendor-scorecard",
    "description": "FEC-OS API: compliance / vendor-scorecard",
    "categoryId": "compliance",
    "categoryLabel": "Compliance",
    "authType": "session",
    "authDetail": "Session + capability: compliance.view"
  },
  {
    "id": "get-api-customer-complaints",
    "method": "GET",
    "path": "/api/customer/complaints",
    "description": "FEC-OS API: customer / complaints",
    "categoryId": "customer",
    "categoryLabel": "Customer",
    "authType": "session",
    "authDetail": "Session + capability: customer.view_complaints"
  },
  {
    "id": "get-api-daily-ops-briefings",
    "method": "GET",
    "path": "/api/daily-ops/briefings",
    "description": "FEC-OS API: daily-ops / briefings",
    "categoryId": "daily-ops",
    "categoryLabel": "Daily Ops",
    "authType": "session",
    "authDetail": "Session + capability: daily_ops.view"
  },
  {
    "id": "get-api-daily-ops-complaints",
    "method": "GET",
    "path": "/api/daily-ops/complaints",
    "description": "FEC-OS API: daily-ops / complaints",
    "categoryId": "daily-ops",
    "categoryLabel": "Daily Ops",
    "authType": "session",
    "authDetail": "Session + capability: daily_ops.view"
  },
  {
    "id": "get-api-daily-ops-incidents",
    "method": "GET",
    "path": "/api/daily-ops/incidents",
    "description": "FEC-OS API: daily-ops / incidents",
    "categoryId": "daily-ops",
    "categoryLabel": "Daily Ops",
    "authType": "session",
    "authDetail": "Session + capability: daily_ops.view"
  },
  {
    "id": "get-api-daily-ops-kpis",
    "method": "GET",
    "path": "/api/daily-ops/kpis",
    "description": "FEC-OS API: daily-ops / kpis",
    "categoryId": "daily-ops",
    "categoryLabel": "Daily Ops",
    "authType": "session",
    "authDetail": "Session + capability: daily_ops.view"
  },
  {
    "id": "get-api-daily-ops-maintenance",
    "method": "GET",
    "path": "/api/daily-ops/maintenance",
    "description": "FEC-OS API: daily-ops / maintenance",
    "categoryId": "daily-ops",
    "categoryLabel": "Daily Ops",
    "authType": "session",
    "authDetail": "Session + capability: daily_ops.view"
  },
  {
    "id": "get-api-daily-ops-roster",
    "method": "GET",
    "path": "/api/daily-ops/roster",
    "description": "FEC-OS API: daily-ops / roster",
    "categoryId": "daily-ops",
    "categoryLabel": "Daily Ops",
    "authType": "session",
    "authDetail": "Session + capability: daily_ops.view"
  },
  {
    "id": "get-api-dashboard-charts",
    "method": "GET",
    "path": "/api/dashboard/charts",
    "description": "FEC-OS API: dashboard / charts",
    "categoryId": "dashboard",
    "categoryLabel": "Dashboard",
    "authType": "session",
    "authDetail": "Session + capability: dashboard.view"
  },
  {
    "id": "get-api-dashboard-kpis",
    "method": "GET",
    "path": "/api/dashboard/kpis",
    "description": "FEC-OS API: dashboard / kpis",
    "categoryId": "dashboard",
    "categoryLabel": "Dashboard",
    "authType": "session",
    "authDetail": "Session + capability: dashboard.view"
  },
  {
    "id": "get-api-dashboard-secondary",
    "method": "GET",
    "path": "/api/dashboard/secondary",
    "description": "FEC-OS API: dashboard / secondary",
    "categoryId": "dashboard",
    "categoryLabel": "Dashboard",
    "authType": "session",
    "authDetail": "Session cookie"
  },
  {
    "id": "get-api-facility-tasks",
    "method": "GET",
    "path": "/api/facility/tasks",
    "description": "FEC-OS API: facility / tasks",
    "categoryId": "facility",
    "categoryLabel": "Facility",
    "authType": "session",
    "authDetail": "Session + capability: facility.view"
  },
  {
    "id": "get-api-inspections",
    "method": "GET",
    "path": "/api/inspections",
    "description": "Inspections map to AMC service schedules (PM / verification visits).",
    "categoryId": "inspections",
    "categoryLabel": "Inspections",
    "authType": "session",
    "authDetail": "Session + capability: amc.view"
  },
  {
    "id": "get-api-inventory",
    "method": "GET",
    "path": "/api/inventory",
    "description": "FEC-OS API: inventory",
    "categoryId": "inventory",
    "categoryLabel": "Inventory",
    "authType": "session",
    "authDetail": "Session + capability: inventory.view"
  },
  {
    "id": "get-api-inventory-dashboard",
    "method": "GET",
    "path": "/api/inventory/dashboard",
    "description": "FEC-OS API: inventory / dashboard",
    "categoryId": "inventory",
    "categoryLabel": "Inventory",
    "authType": "session",
    "authDetail": "Session + capability: inventory.view"
  },
  {
    "id": "get-api-issues",
    "method": "GET",
    "path": "/api/issues",
    "description": "FEC-OS API: issues",
    "categoryId": "issues",
    "categoryLabel": "Issues",
    "authType": "session",
    "authDetail": "Session + capability: issues.view"
  },
  {
    "id": "get-api-maintenance-dashboard",
    "method": "GET",
    "path": "/api/maintenance/dashboard",
    "description": "FEC-OS API: maintenance / dashboard",
    "categoryId": "maintenance",
    "categoryLabel": "Maintenance",
    "authType": "session",
    "authDetail": "Session + capability: maintenance.view"
  },
  {
    "id": "get-api-maintenance-downtime",
    "method": "GET",
    "path": "/api/maintenance/downtime",
    "description": "FEC-OS API: maintenance / downtime",
    "categoryId": "maintenance",
    "categoryLabel": "Maintenance",
    "authType": "session",
    "authDetail": "Session + capability: maintenance.view"
  },
  {
    "id": "get-api-maintenance-pm-schedules",
    "method": "GET",
    "path": "/api/maintenance/pm-schedules",
    "description": "FEC-OS API: maintenance / pm-schedules",
    "categoryId": "maintenance",
    "categoryLabel": "Maintenance",
    "authType": "session",
    "authDetail": "Session + capability: maintenance.view"
  },
  {
    "id": "get-api-maintenance-weekly-report",
    "method": "GET",
    "path": "/api/maintenance/weekly-report",
    "description": "FEC-OS API: maintenance / weekly-report",
    "categoryId": "maintenance",
    "categoryLabel": "Maintenance",
    "authType": "session",
    "authDetail": "Session + capability: maintenance.weekly_report"
  },
  {
    "id": "get-api-maintenance-weekly-reports",
    "method": "GET",
    "path": "/api/maintenance/weekly-reports",
    "description": "FEC-OS API: maintenance / weekly-reports",
    "categoryId": "maintenance",
    "categoryLabel": "Maintenance",
    "authType": "session",
    "authDetail": "Session + any of: maintenance.weekly_report, maintenance.weekly_report.submit, maintenance.logistics_submit, maintenance.weekly_report.review, maintenance.weekly_report.executive"
  },
  {
    "id": "get-api-maintenance-weekly-reports-id",
    "method": "GET",
    "path": "/api/maintenance/weekly-reports/{id}",
    "description": "FEC-OS API: maintenance / weekly-reports / {id}",
    "categoryId": "maintenance",
    "categoryLabel": "Maintenance",
    "authType": "session",
    "authDetail": "Session + any of: maintenance.weekly_report, maintenance.weekly_report.submit, maintenance.logistics_submit, maintenance.weekly_report.review, maintenance.weekly_report.executive"
  },
  {
    "id": "get-api-maintenance-weekly-reports-executive",
    "method": "GET",
    "path": "/api/maintenance/weekly-reports/executive",
    "description": "FEC-OS API: maintenance / weekly-reports / executive",
    "categoryId": "maintenance",
    "categoryLabel": "Maintenance",
    "authType": "session",
    "authDetail": "Session + capability: maintenance.weekly_report.executive"
  },
  {
    "id": "get-api-notifications",
    "method": "GET",
    "path": "/api/notifications",
    "description": "FEC-OS API: notifications",
    "categoryId": "notifications",
    "categoryLabel": "Notifications",
    "authType": "session",
    "authDetail": "Session + any of: issues.view, notifications.view"
  },
  {
    "id": "get-api-notifications-escalations",
    "method": "GET",
    "path": "/api/notifications/escalations",
    "description": "FEC-OS API: notifications / escalations",
    "categoryId": "notifications",
    "categoryLabel": "Notifications",
    "authType": "session",
    "authDetail": "Session + capability: issues.view"
  },
  {
    "id": "get-api-occ-branch",
    "method": "GET",
    "path": "/api/occ/branch",
    "description": "FEC-OS API: occ / branch",
    "categoryId": "occ",
    "categoryLabel": "OCC",
    "authType": "session",
    "authDetail": "Session + capability: occ.view_branch"
  },
  {
    "id": "get-api-occ-exceptions",
    "method": "GET",
    "path": "/api/occ/exceptions",
    "description": "FEC-OS API: occ / exceptions",
    "categoryId": "occ",
    "categoryLabel": "OCC",
    "authType": "session",
    "authDetail": "Session + capability: occ.view_estate"
  },
  {
    "id": "get-api-occ-handover",
    "method": "GET",
    "path": "/api/occ/handover",
    "description": "FEC-OS API: occ / handover",
    "categoryId": "occ",
    "categoryLabel": "OCC",
    "authType": "session",
    "authDetail": "Session + capability: occ.view_branch"
  },
  {
    "id": "get-api-occ-rollup",
    "method": "GET",
    "path": "/api/occ/rollup",
    "description": "FEC-OS API: occ / rollup",
    "categoryId": "occ",
    "categoryLabel": "OCC",
    "authType": "session",
    "authDetail": "Session + capability: occ.view_estate"
  },
  {
    "id": "get-api-operations-branches",
    "method": "GET",
    "path": "/api/operations/branches",
    "description": "FEC-OS API: operations / branches",
    "categoryId": "operations",
    "categoryLabel": "Operations",
    "authType": "session",
    "authDetail": "Session + capability: dashboard.view"
  },
  {
    "id": "get-api-operations-dashboard",
    "method": "GET",
    "path": "/api/operations/dashboard",
    "description": "FEC-OS API: operations / dashboard",
    "categoryId": "operations",
    "categoryLabel": "Operations",
    "authType": "session",
    "authDetail": "Session + capability: dashboard.view"
  },
  {
    "id": "get-api-operations-site-summary",
    "method": "GET",
    "path": "/api/operations/site-summary",
    "description": "FEC-OS API: operations / site-summary",
    "categoryId": "operations",
    "categoryLabel": "Operations",
    "authType": "session",
    "authDetail": "Session + capability: dashboard.view"
  },
  {
    "id": "get-api-people",
    "method": "GET",
    "path": "/api/people",
    "description": "FEC-OS API: people",
    "categoryId": "people",
    "categoryLabel": "People",
    "authType": "session",
    "authDetail": "Session + capability: people.view_roster"
  },
  {
    "id": "get-api-people-dashboard",
    "method": "GET",
    "path": "/api/people/dashboard",
    "description": "FEC-OS API: people / dashboard",
    "categoryId": "people",
    "categoryLabel": "People",
    "authType": "session",
    "authDetail": "Session + capability: people.view_roster"
  },
  {
    "id": "get-api-people-departments",
    "method": "GET",
    "path": "/api/people/departments",
    "description": "FEC-OS API: people / departments",
    "categoryId": "people",
    "categoryLabel": "People",
    "authType": "session",
    "authDetail": "Session + capability: people.view_roster"
  },
  {
    "id": "get-api-people-shifts",
    "method": "GET",
    "path": "/api/people/shifts",
    "description": "FEC-OS API: people / shifts",
    "categoryId": "people",
    "categoryLabel": "People",
    "authType": "session",
    "authDetail": "Session + capability: people.view_roster"
  },
  {
    "id": "post-api-public-attendance-ingest",
    "method": "POST",
    "path": "/api/public/attendance-ingest",
    "description": "External attendance data ingestion (HR / biometric exports).",
    "categoryId": "public",
    "categoryLabel": "Public & Cron",
    "authType": "api_key",
    "authDetail": "ATTENDANCE_INGEST_API_KEY (Bearer or X-API-Key)",
    "exampleRequest": {
      "headers": {
        "Content-Type": "application/json",
        "X-API-Key": "<ATTENDANCE_INGEST_API_KEY>"
      },
      "body": {
        "records": [
          {
            "location": "Urban Arena - Doha Mall",
            "user_name": "Waqar",
            "date": "23-06-2026",
            "first_check_in": "2:27:51 PM",
            "last_check_out": null,
            "total_hours_worked": 0,
            "overtime": false,
            "overtime_hours": 0,
            "status": "Missing Punch"
          }
        ]
      }
    }
  },
  {
    "id": "post-api-public-attendance-sync",
    "method": "POST",
    "path": "/api/public/attendance-sync",
    "description": "Middleware-ready attendance sync endpoint (ZKTeco / biometric devices).",
    "categoryId": "public",
    "categoryLabel": "Public & Cron",
    "authType": "cron_secret",
    "authDetail": "CRON_SECRET (Bearer or x-cron-secret)",
    "exampleRequest": {
      "headers": {
        "Content-Type": "application/json",
        "Authorization": "Bearer <CRON_SECRET>"
      },
      "body": {
        "location_id": "<uuid>",
        "device_code": "ZK-001",
        "records": [
          {
            "biometric_user_id": "1001",
            "punch_at": "2026-06-29T09:00:00Z",
            "punch_type": "in"
          }
        ]
      }
    }
  },
  {
    "id": "post-api-public-bookingqube-sync",
    "method": "POST",
    "path": "/api/public/bookingqube-sync",
    "description": "Cron-ready: POST /api/public/bookingqube-sync",
    "categoryId": "public",
    "categoryLabel": "Public & Cron",
    "authType": "cron_secret",
    "authDetail": "CRON_SECRET (Bearer or x-cron-secret)",
    "exampleRequest": {
      "headers": {
        "Authorization": "Bearer <CRON_SECRET>"
      },
      "body": {
        "from": "2026-06-01",
        "to": "2026-06-30"
      }
    }
  },
  {
    "id": "post-api-public-escalation-sweep",
    "method": "POST",
    "path": "/api/public/escalation-sweep",
    "description": "FEC-OS API: public / escalation-sweep",
    "categoryId": "public",
    "categoryLabel": "Public & Cron",
    "authType": "cron_secret",
    "authDetail": "CRON_SECRET (Bearer or x-cron-secret)"
  },
  {
    "id": "post-api-public-maintenance-sla-sweep",
    "method": "POST",
    "path": "/api/public/maintenance-sla-sweep",
    "description": "FEC-OS API: public / maintenance-sla-sweep",
    "categoryId": "public",
    "categoryLabel": "Public & Cron",
    "authType": "cron_secret",
    "authDetail": "CRON_SECRET (Bearer or x-cron-secret)"
  },
  {
    "id": "get-api-revenue-asset-roi",
    "method": "GET",
    "path": "/api/revenue/asset-roi",
    "description": "FEC-OS API: revenue / asset-roi",
    "categoryId": "revenue",
    "categoryLabel": "Revenue",
    "authType": "session",
    "authDetail": "Session + capability: revenue.view"
  },
  {
    "id": "get-api-revenue-leakage",
    "method": "GET",
    "path": "/api/revenue/leakage",
    "description": "FEC-OS API: revenue / leakage",
    "categoryId": "revenue",
    "categoryLabel": "Revenue",
    "authType": "session",
    "authDetail": "Session + capability: revenue.view"
  },
  {
    "id": "get-api-revenue-monthly-progress",
    "method": "GET",
    "path": "/api/revenue/monthly-progress",
    "description": "FEC-OS API: revenue / monthly-progress",
    "categoryId": "revenue",
    "categoryLabel": "Revenue",
    "authType": "session",
    "authDetail": "Session + capability: revenue.view"
  },
  {
    "id": "get-api-revenue-pace",
    "method": "GET",
    "path": "/api/revenue/pace",
    "description": "FEC-OS API: revenue / pace",
    "categoryId": "revenue",
    "categoryLabel": "Revenue",
    "authType": "session",
    "authDetail": "Session + capability: revenue.view"
  },
  {
    "id": "get-api-revenue-pnl",
    "method": "GET",
    "path": "/api/revenue/pnl",
    "description": "FEC-OS API: revenue / pnl",
    "categoryId": "revenue",
    "categoryLabel": "Revenue",
    "authType": "session",
    "authDetail": "Session + capability: revenue.view"
  },
  {
    "id": "get-api-revenue-sync-status",
    "method": "GET",
    "path": "/api/revenue/sync-status",
    "description": "FEC-OS API: revenue / sync-status",
    "categoryId": "revenue",
    "categoryLabel": "Revenue",
    "authType": "session",
    "authDetail": "Session + capability: revenue.view"
  },
  {
    "id": "get-api-risk",
    "method": "GET",
    "path": "/api/risk",
    "description": "FEC-OS API: risk",
    "categoryId": "risk",
    "categoryLabel": "Risk",
    "authType": "session",
    "authDetail": "Session + capability: risk.view"
  },
  {
    "id": "get-api-sites",
    "method": "GET",
    "path": "/api/sites",
    "description": "FEC-OS API: sites",
    "categoryId": "sites",
    "categoryLabel": "Sites",
    "authType": "session",
    "authDetail": "Session + capability: dashboard.view"
  },
  {
    "id": "get-api-snags",
    "method": "GET",
    "path": "/api/snags",
    "description": "FEC-OS API: snags",
    "categoryId": "snags",
    "categoryLabel": "Snags",
    "authType": "session",
    "authDetail": "Session + capability: snags.view"
  },
  {
    "id": "get-api-snags-id",
    "method": "GET",
    "path": "/api/snags/{id}",
    "description": "FEC-OS API: snags / {id}",
    "categoryId": "snags",
    "categoryLabel": "Snags",
    "authType": "session",
    "authDetail": "Session + capability: snags.view"
  },
  {
    "id": "get-api-tasks",
    "method": "GET",
    "path": "/api/tasks",
    "description": "FEC-OS API: tasks",
    "categoryId": "tasks",
    "categoryLabel": "Tasks",
    "authType": "session",
    "authDetail": "Session + capability: tasks.view"
  },
  {
    "id": "get-api-utilities",
    "method": "GET",
    "path": "/api/utilities",
    "description": "FEC-OS API: utilities",
    "categoryId": "utilities",
    "categoryLabel": "Utilities",
    "authType": "session",
    "authDetail": "Session + capability: utilities.view"
  },
  {
    "id": "get-api-vendors",
    "method": "GET",
    "path": "/api/vendors",
    "description": "FEC-OS API: vendors",
    "categoryId": "vendors",
    "categoryLabel": "Vendors",
    "authType": "session",
    "authDetail": "Session + capability: vendors.view"
  },
  {
    "id": "get-api-vendors-dashboard",
    "method": "GET",
    "path": "/api/vendors/dashboard",
    "description": "FEC-OS API: vendors / dashboard",
    "categoryId": "vendors",
    "categoryLabel": "Vendors",
    "authType": "session",
    "authDetail": "Session + capability: vendors.view"
  },
  {
    "id": "get-api-weekly-reports",
    "method": "GET",
    "path": "/api/weekly-reports",
    "description": "FEC-OS API: weekly-reports",
    "categoryId": "weekly-reports",
    "categoryLabel": "Weekly Reports",
    "authType": "session",
    "authDetail": "Session + capability: weekly_reports.view"
  },
  {
    "id": "get-api-weekly-reports-id",
    "method": "GET",
    "path": "/api/weekly-reports/{id}",
    "description": "FEC-OS API: weekly-reports / {id}",
    "categoryId": "weekly-reports",
    "categoryLabel": "Weekly Reports",
    "authType": "session",
    "authDetail": "Session + capability: weekly_reports.view"
  },
  {
    "id": "get-api-weekly-reports-executive",
    "method": "GET",
    "path": "/api/weekly-reports/executive",
    "description": "FEC-OS API: weekly-reports / executive",
    "categoryId": "weekly-reports",
    "categoryLabel": "Weekly Reports",
    "authType": "session",
    "authDetail": "Session + capability: weekly_reports.executive"
  },
  {
    "id": "get-api-weekly-reports-executive-kpis",
    "method": "GET",
    "path": "/api/weekly-reports/executive/kpis",
    "description": "FEC-OS API: weekly-reports / executive / kpis",
    "categoryId": "weekly-reports",
    "categoryLabel": "Weekly Reports",
    "authType": "session",
    "authDetail": "Session + capability: weekly_reports.executive"
  },
  {
    "id": "get-api-work-orders",
    "method": "GET",
    "path": "/api/work-orders",
    "description": "FEC-OS API: work-orders",
    "categoryId": "work-orders",
    "categoryLabel": "Work Orders",
    "authType": "session",
    "authDetail": "Session + capability: maintenance.view"
  }
];

export const API_ENDPOINT_COUNT = 103;
