-- Replace staff directory with spreadsheet import (61 records)
-- Generated by scripts/generate-staff-replace-migration.mjs

-- Ensure Kids Mini (Doha Mall) and Winter Mirage (Vendome) locations exist
INSERT INTO public.locations (code, name, city, region, country, timezone, status, launched_on) VALUES
  ('KDS-DM', 'Kids Mini Driving School', 'Doha', 'Doha Mall', 'QA', 'Asia/Qatar', 'active', '2022-04-01'),
  ('WM-VM', 'Winter Mirage', 'Doha', 'Vendome Mall', 'QA', 'Asia/Qatar', 'active', '2026-04-22')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  city = EXCLUDED.city,
  status = EXCLUDED.status,
  updated_at = now();

ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS qid text;

-- Clear staff-linked records before full directory replace
DELETE FROM public.training_enrollments;
DELETE FROM public.attendance_exceptions;
DELETE FROM public.attendance_daily_summary;
DELETE FROM public.attendance_logs;
DELETE FROM public.sop_assignments WHERE staff_id IS NOT NULL;
DELETE FROM public.kpi_scores WHERE staff_id IS NOT NULL;
DELETE FROM public.kpi_assignments WHERE staff_id IS NOT NULL;
UPDATE public.shifts SET staff_id = NULL;
DELETE FROM public.staff;

INSERT INTO public.staff (
  id,
  location_id,
  employee_code,
  full_name,
  job_title,
  department,
  hire_date,
  status,
  phone,
  staff_role,
  qid
)
SELECT
  v.id::uuid,
  l.id,
  v.employee_code,
  v.full_name,
  v.job_title,
  v.department,
  v.hire_date::date,
  v.status,
  v.phone,
  v.staff_role,
  v.qid
FROM (
  VALUES
  ('7f7f0100-cdcd-4335-8e9d-ea9b4a1af9e9', 'UA-DM', '29658611062', 'Waqar Asghar', 'Venue Supervisor', 'OverAll', '2026-03-19', 'active', '+97451234705', 'venue_supervisor'::public.staff_role, '29658611062'),
  ('f7de772f-95b9-47d9-82ea-9c6904c5ed82', 'UA-DM', '30173602895', 'Abdallah Osman', 'Cashier', 'Ticketing Counter', '2026-03-19', 'active', '+97431203338', 'cashier'::public.staff_role, '30173602895'),
  ('30a9908f-d976-4167-8c22-704b70853e75', 'UA-DM', '28940402764', 'Margaret Njeri', 'Cashier', 'Ticketing Counter', '2026-03-19', 'active', '+97470180508', 'cashier'::public.staff_role, '28940402764'),
  ('2c5a1ebe-a940-402c-8002-c66f9c03b41d', 'UA-DM', '30258606237', 'Ali Husnain', 'Shift Lead', 'Main Hub', '2026-03-19', 'active', '+97472116976', 'shift_lead'::public.staff_role, '30258606237'),
  ('73a4dbe4-0bca-4fcd-8bb1-2d283bccd910', 'UA-DM', '28935629722', 'Sachin Shetty', 'Shift Lead', 'Battle Arena', '2026-03-19', 'active', '+97433495903', 'shift_lead'::public.staff_role, '28935629722'),
  ('277c696e-1f18-46ae-8fe8-a1c2aa6cb0f3', 'UA-DM', '29573604200', 'Khalid Sami', 'Crew / Attendant', 'Battle Arena', '2026-03-19', 'active', '+97466208780', 'crew'::public.staff_role, '29573604200'),
  ('1306dedc-dcfe-4b89-8875-f60046dfd2db', 'UA-DM', '29758600074', 'Olubummo Tope', 'Crew / Attendant', 'Floor is Lava', '2026-03-19', 'active', '+97471032078', 'crew'::public.staff_role, '29758600074'),
  ('772d9885-9f5a-4c2c-896d-1fafb5fb4a72', 'UA-DM', '28740403764', 'Lillian Kerubo', 'Crew / Attendant', 'Mini Golf', '2026-03-19', 'active', '+97431562882', 'crew'::public.staff_role, '28740403764'),
  ('cbc9619b-c8b7-4cb4-87bd-0835430f9557', 'UA-DM', '28140401069', 'Goretty Mania', 'Crew / Attendant', 'Mini Golf', '2026-03-19', 'active', '+97433044002', 'crew'::public.staff_role, '28140401069'),
  ('29602f52-15f1-4215-8395-38519ac3f841', 'UA-DM', '28528801171', 'Yebach Ruth', 'Crew / Attendant', 'Trampoline', '2026-03-19', 'active', '+97477969403', 'crew'::public.staff_role, '28528801171'),
  ('8393fd38-a739-4ce2-869f-4bf5480fc4f9', 'UA-DM', '28360812913', 'Rosie Bartocillo', 'Crew / Attendant', 'Kids Tribe', '2026-03-19', 'active', '+97431166270', 'crew'::public.staff_role, '28360812913'),
  ('6ee65a72-6fb5-41dd-8fa0-ce9fc9f80ddc', 'UA-DM', '28460829086', 'Katrina Piscoco', 'Crew / Attendant', 'Kids Tribe', '2026-03-19', 'active', '+97455188491', 'crew'::public.staff_role, '28460829086'),
  ('b7c70b1f-69ab-4678-8fba-22b7f4f6b64d', 'UA-DM', '29052451113', 'Saraswati Chhetri', 'Crew / Attendant', 'Kids Tribe', '2026-03-19', 'active', '+97471431918', 'crew'::public.staff_role, '29052451113'),
  ('af46c439-4c42-4334-81de-a60d4ae5ba95', 'UA-DM', '29858612703', 'Wahaj Asghar', 'Crew / Attendant', 'Go kart+Acade Games', '2026-03-19', 'active', '+97477599149', 'crew'::public.staff_role, '29858612703'),
  ('74f11548-d4aa-47c1-81cb-74760b111350', 'UA-DM', '29358613060', 'Waseem Qayyum', 'Crew / Attendant', 'Go kart+Acade Games', '2026-03-19', 'active', '+97452041997', 'crew'::public.staff_role, '29358613060'),
  ('b18a7e16-4af2-4c52-8709-1a3754038bd9', 'UA-DM', '30052418835', 'Rajan Khadka', 'Crew / Attendant', 'Go kart+Acade Games', '2026-03-19', 'active', '+97474763754', 'crew'::public.staff_role, '30052418835'),
  ('291cae90-7e67-48c3-8155-6c6064a9435b', 'UA-DM', '30035005493', 'MD Juber Hussain', 'Crew / Attendant', 'Archery', '2026-03-19', 'active', '+97477800738', 'crew'::public.staff_role, '30035005493'),
  ('cd64f5c1-cb52-489c-8d60-bfb38829b5bb', 'UA-DM', '29852419561', 'Mokarm khursaid', 'Crew / Attendant', 'Hoopshots+Billiards', '2026-03-19', 'active', '+97477057028', 'crew'::public.staff_role, '29852419561'),
  ('5b122dc4-7339-405b-8d70-723b510c5a92', 'UA-DM', '30460800753', 'Abdi Shakur Omar', 'Crew / Attendant', 'Ar Racing+SpinCity+Ping Pong', '2026-03-19', 'active', '+97430467113', 'crew'::public.staff_role, '30460800753'),
  ('00462ed2-ad65-4b15-87b7-ac6a7662ba1a', 'UA-DM', '30260800711', 'Hussain omar', 'Crew / Attendant', 'Dartxxx+Ax+Herox+PSS', '2026-03-19', 'active', '+97451060223', 'crew'::public.staff_role, '30260800711'),
  ('be1a68eb-6004-4865-8ede-2f9f16a0d08c', 'UA-DM', '28405028554', 'Hannan Abid', 'Technician', 'Maintenance', '2026-03-19', 'active', '+97450857821', 'technician'::public.staff_role, '28405028554'),
  ('ca24877b-3a5d-4eed-8f61-b1b1a3d784c8', 'CB-DSM', '28360804725', 'Romel Chavez Pusung', 'Venue Supervisor', NULL, '2022-09-03', 'active', '+97455683711', 'venue_supervisor'::public.staff_role, '28360804725'),
  ('edce4116-3785-4a40-82eb-03671cf531eb', 'CB-DSM', '27460807049', 'Mary rose Bustamante', 'Artist', NULL, '2024-12-01', 'active', '+97433900174', 'other'::public.staff_role, '27460807049'),
  ('3d70b35c-ca9b-45c8-82c2-d212b065db09', 'CB-DSM', '29058615118', 'Abdul Qadir Sayed Khan', 'Crew / Attendant', NULL, '2026-06-28', 'active', '+97466003460', 'crew'::public.staff_role, '29058615118'),
  ('3a83abc7-d562-4e7b-8cbb-18f119a7ea8f', 'CAR-AP', '28858608039', 'Zaryab Javaid', 'Venue Supervisor', NULL, '2024-03-01', 'active', '+97470603084', 'venue_supervisor'::public.staff_role, '28858608039'),
  ('95de8a7c-7340-4307-837a-18914f439046', 'CAR-AP', '28460807725', 'Flora Mae', 'Crew / Attendant', NULL, '2024-07-01', 'active', '+97430613987', 'crew'::public.staff_role, '28460807725'),
  ('ae05f4e8-1ad7-4edc-8a5d-d75485a71965', 'KDS-DM', '30173602675', 'Mazin Abdelazeem', 'Cashier', NULL, '2026-06-18', 'active', '+97471858412', 'cashier'::public.staff_role, '30173602675'),
  ('66f389a8-f8c7-4305-8296-58a4db45d41e', 'KDS-DM', '29558611657', 'Rizwan Hassan', 'Crew / Attendant', NULL, '2026-06-18', 'active', '+97470212910', 'crew'::public.staff_role, '29558611657'),
  ('72bc11c4-6984-4aaf-8213-22647a2f15ab', 'KDS-DM', '29640401505', 'Hannah Wakio', 'Crew / Attendant', NULL, '2026-06-18', 'active', '+97466166052', 'crew'::public.staff_role, '29640401505'),
  ('cc3de8f3-2ce8-4bcf-8db6-3e15be5fdfb3', 'KDS-CC', '28656600858', 'Abiola Moses Ogunniyi', 'Crew / Attendant', 'Driving Lane/ Yalla Toys', '2025-06-06', 'active', '+97471047512', 'crew'::public.staff_role, '28656600858'),
  ('212e4a98-2511-473e-8118-1a6b0175cb6b', 'KDS-CC', '29040406440', 'Mary Nyambura', 'Crew / Attendant', 'Soft Play', '2025-06-06', 'active', '+97455381246', 'crew'::public.staff_role, '29040406440'),
  ('68645f15-b178-47e6-834a-295f68e48e3a', 'KDS-CC', '27260808749', 'Nemeta Sablo Cabrera', 'Crew / Attendant', 'Ballpit', '2025-06-06', 'active', '+97431531672', 'crew'::public.staff_role, '27260808749'),
  ('7adab94b-3dbd-4c8c-83ad-eae22f041eab', 'KDS-CC', '30052413225', 'Pabitra Acharya', 'Crew / Attendant', 'Ticket Checking', '2025-06-06', 'active', '+97471273620', 'crew'::public.staff_role, '30052413225'),
  ('7312e8d1-3793-4ea7-812e-7ee8bca26387', 'KDS-CC', '29656600197', 'Noah Cini', 'Crew / Attendant', 'Driving Lane', '2025-06-06', 'active', '+97433998621', 'crew'::public.staff_role, '29656600197'),
  ('b83836a9-c59d-41cc-8b60-c2e34905fd18', 'KDS-CC', '29328801301', 'Abigail Danso kumi', 'Crew / Attendant', 'Ticket Checking', '2025-06-06', 'active', '+97471844636', 'crew'::public.staff_role, '29328801301'),
  ('86ac5265-55c2-4fbb-8b1c-08016d0fe52d', 'KDS-CC', '29405011077', 'Uzzal Mia Alkas mia', 'Cleaner', 'Driving lane', '2025-06-06', 'active', '+97430295614', 'cleaner'::public.staff_role, '29405011077'),
  ('b6bb7fcc-5f1a-4cdf-8730-43604540cf61', 'KDS-CC', '29628801124', 'Sahadatu Bawa', 'Crew / Attendant', 'Ballpit', '2025-10-05', 'active', '+97431349462', 'crew'::public.staff_role, '29628801124'),
  ('2edf1270-0cea-418e-882d-bed224187919', 'KDS-CC', '29852424131', 'Sujata Sigdel', 'Crew / Attendant', 'Soft Play', '2025-06-06', 'active', '+97431338038', 'crew'::public.staff_role, '29852424131'),
  ('6518e2dc-5301-40e7-8b70-57e6a0ebb20c', 'KDS-CC', '29973602805', 'Mohammed Abdelazeem M', 'Cashier', 'Cashier', '2025-06-06', 'active', '+97430425191', 'cashier'::public.staff_role, '29973602805'),
  ('72de7e5e-85f2-43bb-8632-a0fdd2d02e76', 'KDS-CC', '28460812356', 'Rodelyn Loria Marbida', 'Cashier', 'Vacation', '2025-06-06', 'on_leave', '+97450909843', 'cashier'::public.staff_role, '28460812356'),
  ('846a6f98-d7ba-46b1-80e1-9a5f80742b23', 'KDS-CC', '30358609483', 'Atif Ali Munir Ahmed', 'Cashier', 'Cashier', '2025-06-06', 'active', '+97474461584', 'cashier'::public.staff_role, '30358609483'),
  ('96cab0be-7ce9-4513-82bf-2a083bacffbe', 'KDS-CC', '29735603636', 'Ashfaq Noori', 'Venue Supervisor', NULL, '2025-06-06', 'active', '+97430214432', 'venue_supervisor'::public.staff_role, '29735603636'),
  ('c28c50c7-a580-4efd-8448-601f0364b689', 'CB-VM', '29660800835', 'Rosebelt Fatal', 'Venue Supervisor', NULL, '2023-11-22', 'active', '+97466720880', 'venue_supervisor'::public.staff_role, '29660800835'),
  ('228428ac-d084-4374-87eb-dfb938a2c211', 'CB-VM', '28460818555', 'Irene Pabello', 'Artist', NULL, '2023-11-22', 'active', '+97477837120', 'other'::public.staff_role, '28460818555'),
  ('a4852cb5-8f94-4efd-8e37-5a066eae06d6', 'CB-VM', '29560801403', 'Charlene Jeanne Agapito', 'Artist', NULL, '2023-11-22', 'active', '+97431824899', 'other'::public.staff_role, '29560801403'),
  ('6bd01d09-18e5-403f-8786-39623bb25d48', 'CB-VM', '29852425598', 'Avishek Pandit', 'Artist', NULL, '2024-03-10', 'active', '+97430399891', 'other'::public.staff_role, '29852425598'),
  ('b4aedad5-3481-4595-8c23-c2064a2b9ef8', 'WM-VM', '29701201238', 'Rabah Aberrraouf Belhadj', 'Technician', NULL, '2026-04-22', 'active', '+97451247628', 'technician'::public.staff_role, '29701201238'),
  ('b1cad8f7-e312-4c8c-8b34-97759eb86013', 'WM-VM', '29501201428', 'Mohamed Islem Bettin', 'Technician', NULL, NULL, 'active', '+97430224214', 'technician'::public.staff_role, '29501201428'),
  ('5c293fe6-6ece-4fab-8506-1fe1c7d66bb8', 'INF-CC', '29440401419', 'Mary Muiruri', 'Venue Supervisor', NULL, '2022-05-15', 'active', '+97466269506', 'venue_supervisor'::public.staff_role, '29440401419'),
  ('1a900de1-f5ac-40ab-8317-afe445d61787', 'INF-CC', '28760810436', 'Mercy Galang Garcia', 'Cashier', 'Cashier', '2022-05-15', 'active', '+97433927495', 'cashier'::public.staff_role, '28760810436'),
  ('872ee2fd-5e95-4d14-8074-b4b9579260b2', 'INF-CC', '28460819794', 'Jorene Tesoro Quixote', 'Cashier', 'Cashier', '2022-02-25', 'active', '+97450541839', 'cashier'::public.staff_role, '28460819794'),
  ('df283e23-427f-4745-82e8-a3ae39d1dc7a', 'INF-CC', '29160813855', 'Angie Urania santos', 'Crew / Attendant', 'INFLATA park', '2022-05-25', 'active', '+97450217980', 'crew'::public.staff_role, '29160813855'),
  ('e432fc42-938c-411d-8830-3f71ac6f0c92', 'INF-CC', '29360802506', 'Marissa Domingo Reyes', 'Cashier', 'Cashier', '2022-05-25', 'active', '+97431559302', 'cashier'::public.staff_role, '29360802506'),
  ('e8146c37-d243-462b-8e64-922cb28a8193', 'INF-CC', '28214407767', 'Wasanthi Hemamali', 'Crew / Attendant', 'INFLATA park', '2024-02-12', 'active', '+97455395068', 'crew'::public.staff_role, '28214407767'),
  ('b2727742-c2cf-4232-820b-41c0616a06c6', 'INF-CC', '28860814283', 'Maanaliza Quijote', 'Crew / Attendant', 'Grab and win', '2022-05-20', 'active', '+97452061452', 'crew'::public.staff_role, '28860814283'),
  ('ce0f6628-2060-4395-8fc4-d4827b8de71f', 'INF-CC', '28760825747', 'Ma luz Jesus Romeo', 'Crew / Attendant', 'Space tribe', '2022-05-20', 'active', '+97430151347', 'crew'::public.staff_role, '28760825747'),
  ('71fc1263-74c0-43b9-8011-0e79a9ee57da', 'INF-CC', '28352414399', 'Mani raj pariyar', 'Crew / Attendant', 'Battle arena', '2023-02-11', 'active', '+97470847131', 'crew'::public.staff_role, '28352414399'),
  ('a72a168c-0a15-4ae4-8ca7-38fc1dffc43d', 'INF-CC', '28940403887', 'Philis Mumbi kamau', 'Crew / Attendant', 'Inflate kids', '2022-05-15', 'active', '+97472086076', 'crew'::public.staff_role, '28940403887'),
  ('789ce9ce-4a38-4480-8803-dd526531296f', 'INF-CC', '28328800915', 'Judith appiah', 'Crew / Attendant', 'Space tribe', '2025-06-04', 'active', '+97431066825', 'crew'::public.staff_role, '28328800915'),
  ('c09240d8-d9ff-4f2d-8bf0-219c5b1133a8', 'INF-CC', '29240405361', 'Flora chepchumba', 'Crew / Attendant', 'Battle arena', '2022-05-20', 'active', '+97472055373', 'crew'::public.staff_role, '29240405361'),
  ('f96293ec-ecff-479e-86c7-6d1c100fba16', 'INF-CC', '29060817662', 'Florjana kamentodang', 'Crew / Attendant', 'Inflata park', '2022-05-20', 'active', '+97439912136', 'crew'::public.staff_role, '29060817662')
) AS v(id, loc_code, employee_code, full_name, job_title, department, hire_date, status, phone, staff_role, qid)
JOIN public.locations l ON l.code = v.loc_code;
